/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	egressipv1 "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/egressip/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeEgressIPs implements EgressIPInterface
type FakeEgressIPs struct {
	Fake *FakeK8sV1
	ns   string
}

var egressipsResource = schema.GroupVersionResource{Group: "k8s.ovn.org", Version: "v1", Resource: "egressips"}

var egressipsKind = schema.GroupVersionKind{Group: "k8s.ovn.org", Version: "v1", Kind: "EgressIP"}

// Get takes name of the egressIP, and returns the corresponding egressIP object, and an error if there is any.
func (c *FakeEgressIPs) Get(name string, options v1.GetOptions) (result *egressipv1.EgressIP, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(egressipsResource, c.ns, name), &egressipv1.EgressIP{})

	if obj == nil {
		return nil, err
	}
	return obj.(*egressipv1.EgressIP), err
}

// List takes label and field selectors, and returns the list of EgressIPs that match those selectors.
func (c *FakeEgressIPs) List(opts v1.ListOptions) (result *egressipv1.EgressIPList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(egressipsResource, egressipsKind, c.ns, opts), &egressipv1.EgressIPList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &egressipv1.EgressIPList{ListMeta: obj.(*egressipv1.EgressIPList).ListMeta}
	for _, item := range obj.(*egressipv1.EgressIPList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested egressIPs.
func (c *FakeEgressIPs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(egressipsResource, c.ns, opts))

}

// Create takes the representation of a egressIP and creates it.  Returns the server's representation of the egressIP, and an error, if there is any.
func (c *FakeEgressIPs) Create(egressIP *egressipv1.EgressIP) (result *egressipv1.EgressIP, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(egressipsResource, c.ns, egressIP), &egressipv1.EgressIP{})

	if obj == nil {
		return nil, err
	}
	return obj.(*egressipv1.EgressIP), err
}

// Update takes the representation of a egressIP and updates it. Returns the server's representation of the egressIP, and an error, if there is any.
func (c *FakeEgressIPs) Update(egressIP *egressipv1.EgressIP) (result *egressipv1.EgressIP, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(egressipsResource, c.ns, egressIP), &egressipv1.EgressIP{})

	if obj == nil {
		return nil, err
	}
	return obj.(*egressipv1.EgressIP), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeEgressIPs) UpdateStatus(egressIP *egressipv1.EgressIP) (*egressipv1.EgressIP, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(egressipsResource, "status", c.ns, egressIP), &egressipv1.EgressIP{})

	if obj == nil {
		return nil, err
	}
	return obj.(*egressipv1.EgressIP), err
}

// Delete takes name of the egressIP and deletes it. Returns an error if one occurs.
func (c *FakeEgressIPs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(egressipsResource, c.ns, name), &egressipv1.EgressIP{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeEgressIPs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(egressipsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &egressipv1.EgressIPList{})
	return err
}

// Patch applies the patch and returns the patched egressIP.
func (c *FakeEgressIPs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *egressipv1.EgressIP, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(egressipsResource, c.ns, name, pt, data, subresources...), &egressipv1.EgressIP{})

	if obj == nil {
		return nil, err
	}
	return obj.(*egressipv1.EgressIP), err
}
