/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/egressip/v1"
	scheme "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/egressip/v1/apis/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// EgressIPsGetter has a method to return a EgressIPInterface.
// A group's client should implement this interface.
type EgressIPsGetter interface {
	EgressIPs(namespace string) EgressIPInterface
}

// EgressIPInterface has methods to work with EgressIP resources.
type EgressIPInterface interface {
	Create(*v1.EgressIP) (*v1.EgressIP, error)
	Update(*v1.EgressIP) (*v1.EgressIP, error)
	UpdateStatus(*v1.EgressIP) (*v1.EgressIP, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.EgressIP, error)
	List(opts metav1.ListOptions) (*v1.EgressIPList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.EgressIP, err error)
	EgressIPExpansion
}

// egressIPs implements EgressIPInterface
type egressIPs struct {
	client rest.Interface
	ns     string
}

// newEgressIPs returns a EgressIPs
func newEgressIPs(c *K8sV1Client, namespace string) *egressIPs {
	return &egressIPs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the egressIP, and returns the corresponding egressIP object, and an error if there is any.
func (c *egressIPs) Get(name string, options metav1.GetOptions) (result *v1.EgressIP, err error) {
	result = &v1.EgressIP{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("egressips").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of EgressIPs that match those selectors.
func (c *egressIPs) List(opts metav1.ListOptions) (result *v1.EgressIPList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.EgressIPList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("egressips").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested egressIPs.
func (c *egressIPs) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("egressips").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a egressIP and creates it.  Returns the server's representation of the egressIP, and an error, if there is any.
func (c *egressIPs) Create(egressIP *v1.EgressIP) (result *v1.EgressIP, err error) {
	result = &v1.EgressIP{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("egressips").
		Body(egressIP).
		Do().
		Into(result)
	return
}

// Update takes the representation of a egressIP and updates it. Returns the server's representation of the egressIP, and an error, if there is any.
func (c *egressIPs) Update(egressIP *v1.EgressIP) (result *v1.EgressIP, err error) {
	result = &v1.EgressIP{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("egressips").
		Name(egressIP.Name).
		Body(egressIP).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *egressIPs) UpdateStatus(egressIP *v1.EgressIP) (result *v1.EgressIP, err error) {
	result = &v1.EgressIP{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("egressips").
		Name(egressIP.Name).
		SubResource("status").
		Body(egressIP).
		Do().
		Into(result)
	return
}

// Delete takes name of the egressIP and deletes it. Returns an error if one occurs.
func (c *egressIPs) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("egressips").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *egressIPs) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("egressips").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched egressIP.
func (c *egressIPs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.EgressIP, err error) {
	result = &v1.EgressIP{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("egressips").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
